# -*- coding: utf-8 -*-
"""MEM836_Mechatronics_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-hcwEj3_df1Xq_fR8X7aSuJxy7cfcqIB
"""

!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
# Download YOLOv7 repository and install requirements

# !git clone https://github.com/WongKinYiu/yolov7
# %cd yolov7
# !pip install -r requirements.txt

# current version of YOLOv7 is not compatible with pytorch>1.12.1 and numpy>1.20.1
# until the appropriate changes get made to the main repository, we will be using a fork containing the patched code
# you can track the progress here: https://github.com/roboflow/notebooks/issues/27
!git clone https://github.com/SkalskiP/yolov7.git
# %cd yolov7
!git checkout fix/problems_associated_with_the_latest_versions_of_pytorch_and_numpy
!pip install -r requirements.txt

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="68Dt87s4o0pXo5wvYDSU")
project = rf.workspace("amirabbas-kiani").project("modem-7gguo")
dataset = project.version(1).download("yolov7")

# Commented out IPython magic to ensure Python compatibility.
# download COCO starting checkpoint
# %cd /content/yolov7
!wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-tiny.pt

# Commented out IPython magic to ensure Python compatibility.
# run this cell to begin training
# %cd /content/yolov7
!python train.py --batch 16 --epochs 200 --data {dataset.location}/data.yaml --weights '/content/yolov7/yolov7-tiny.pt' --device 0 --hyp data/hyp.scratch.tiny.yaml

# Run evaluation
!python detect.py --weights runs/train/exp/weights/best.pt --conf 0.1 --source {dataset.location}/test/images

#display inference on ALL test images

import glob
from IPython.display import Image, display

i = 0
limit = 10000 # max images to print
for imageName in glob.glob('/content/yolov7/runs/detect/exp/*.jpg'): #assuming JPG
    if i < limit:
      display(Image(filename=imageName))
      #reader = easyocr.Reader(['en'])
      #result = reader.readtext('filename=imageName',gpu=True)
      print("\n")
    i = i + 1